[window]
title = "Simulação de Pêndulos"
width = 800
height = 800
framerate = 75
background = [0, 0, 0, 255]
font = "res/LiberationMono-Bold.ttf"
font_size = 18

[debug]
show_fps = false
debug_mode = false

[pendulums]
origin = [400, 400]
count = 10000
damping = 0.001

[first_arm]
length = 200
initial_theta = 180
final_theta = 180.5
initial_color = [255, 255, 255, 255]
final_color = [255, 0, 0, 255]
mass = 1

[second_arm]
length = 200
initial_theta = 200
final_theta = 200.5
initial_color = [0, 0, 255, 255]
final_color = [0, 255, 0, 255]
mass = 1
