[window]
title = "Simulação de Pêndulos"
width = 800
height = 800
framerate = 75
maximized = true
background = [0, 0, 0, 255]
font = "res/LiberationMono-Bold.ttf"
font_size = 18

[debug]
show_timer = true
show_fps = false
debug_mode = true
camera_debug = false

[pendulums]
origin = [600, 400]
count = 7500
damping = 0.001

[first_arm]
length = 200
# initial_theta = -210
# final_theta = -210.001
# initial_color = [255, 0, 255, 255]
# final_color = [0, 0, 255, 255]
mass = 1.5

[second_arm]
length = 200
# initial_theta = 200
# final_theta = 200.001
# initial_color = [0, 255, 255, 255]
# final_color = [255, 255, 0, 255]
mass = 1
