[window]
title = "Drag and Drop Example"
width = 800
height = 800
framerate = 75
background = [0, 0, 0, 255]
font = "res/LiberationMono-Bold.ttf"
font_size = 18

[debug]
show_timer = true
show_fps = true
debug_mode = true

[pendulums]
origin = [400, 400]
count = 2
damping = 0.001

[first_arm]
length = 230
initial_theta = 120
final_theta = 121
initial_color = [0, 255, 255, 255]
final_color = [255, 255, 0, 255]
mass = 1

[second_arm]
length = 170
initial_theta = -140
final_theta = -141
initial_color = [0, 255, 255, 255]
final_color = [255, 255, 0, 255]
mass = 1
